### ISSUE TITLE
Fedora 26 does not persist through reboot

### ISSUE THREAD

**Issue by crawfxrd** [datto/dattobd#112]
4.12.13-300.fc26.x86_64

Unsure if this is related to #93, but `/boot/<machine-id>` was removed before installing. `dattobd`, `etc/datto/dla`, and `usr/sbin/datto_reload` are in initramfs.

The module is loaded during boot, but the reload scripts are not run.

**Comment by crawfxrd** [comment]
`$root` is not set, causing [`dattobd.sh`](https://github.com/datto/dattobd/blob/master/dist/initramfs/dracut/dattobd.sh) to exit after loading the module

**Comment by nixomose** [comment]
that's pretty bad, one of the few guarantees in life was that $root was being set. It must have changed to something else, it can't not be made available...

**Comment by crawfxrd** [comment]
I see usage of `[ -z "$root" ] && root=$(getarg root=)` in some other dracut scripts. This appears to work, but I'm not able to find any information on it or `$root`.
