### ISSUE TITLE
dlad: page allocation failure: order:9, mode:0xd0

### ISSUE THREAD

**Issue by DA-SEQ** [datto/dattobd#113]
[datto-oops.txt](https://github.com/datto/dattobd/files/1320784/datto-oops.txt)
Hi,

We are getting a "dlad: page allocation failure" on one of our production systems.

I understand that this is the result of an unsuccessful attempt at allocating memory by __kmalloc(), called by dattobd.ko. But why?

We certainly don't have a memory shortage on that system. Please have a look at the logs attached.

Any help appreciated.

Thanks and regards,
DA

**Comment by tcaputi** [comment]
Are you sure that the system actually experienced a kernel oops? Dattobd has one rather large memory allocation that it performs once per snapshot. For efficiency during operation, we attempt to allocate using `kmalloc()` which attempts to allocate it as one giant chunk of contiguous memory. The system doesn't always have that much contiguous memory available, however, and in that case it falls back to `vmalloc()` which allows the system to use non-contiguous memory.

Unfortunately, the kernel's kmalloc code automatically prints that warning whenever it fails to allocate memory. Now that I'm looking at the kernel code though, it seems that we should be able to suppress this warning. I'll make sure we do that for the next release.

**Comment by DA-SEQ** [comment]
Thanks for the explanation. We do experience backup failures and I thought this was the cause, but if you fallback to vmalloc() then this is probably a red herring. Do you have any procedure to recompile the module to enable debugging?

Thanks,
DA.

**Comment by tcaputi** [comment]
you can enable debugging by setting the module parameter `dattobd_debug=1` at insertion time or after the fact via `echo 1 > /sys/module/dattobd/parameters/dattobd_debug`

**Comment by crawfxrd** [comment]
Resolved in 63c2b6f.
