### ISSUE TITLE
make install for the lib rule effectively fails due to directory target assumption

### ISSUE THREAD

**Issue by OmegaPhil** [datto/dattobd#117]
Devuan Testing here (very similar to Debian) - with v0.10, in 'lib/Makefile' LIBDIR has been changed from '$(PREFIX)/lib' to '$(PREFIX)/lib64'. Since the '/usr/local/lib64' directory doesn't exist (64bit is the default for a long time I think), the install rule ends up installing the shared library itself to the path '/usr/local/lib64'.

I'm not familar with the standard here, but for reference, '/usr/lib/x86_64-linux-gnu' is an example of a 64bit architecture-specific directory, but plenty of stuff is just dumped in '/usr/lib', which is fine for a 64bit machine.

As a workaround, just removing '64' makes it work as usual.

**Comment by Conan-Kudo** [comment]
@OmegaPhil This is not a bug. FHS specifies `lib<qual>` (64 for x86_64) as the standard path. Debian systems use a non-standard convention called "Debian multiarch". When building for Debian, just override the variable.

**Comment by OmegaPhil** [comment]
OK, I will override - it is a bug, for Debian environments - I understand what you're saying regardless. Presumably this is where over-the-top build systems come in (autotools etc).

**Comment by Conan-Kudo** [comment]
@OmegaPhil Usually, yes. As we don't have an automagic build system that debhelper would pass all the right things to, you'll have to do it yourself.

Though, we do provide packages for Debian already, so you could use those.

**Comment by OmegaPhil** [comment]
Thanks, yeah I'm aware of the Ubuntu packages - I prefer to build from source in general (supposedly 'better' trust situation with manual compiles etc).

**Comment by Conan-Kudo** [comment]
Sure, that's fine. Just wanted to let you know we do provide both Ubuntu and Debian packages.
