### ISSUE TITLE
CentOS 5 does not support reload-snapshot or reload-transition case

### ISSUE THREAD

**Issue by yummydsky** [datto/dattobd#125]
How can I handle reload-snapshot and reload-incremental case if CentOS 5 does not support scripts for mkinitrd?

Could you please help? Thanks.

**Comment by crawfxrd** [comment]
This is not possible on EL5. To support tracking through reboots, you would need to update your system.

We are planning to end support for CentOS 5 in the Datto Agent. This issue will be closed by #131.

**Comment by yummydsky** [comment]
Okay, thanks.
