### ISSUE TITLE
Missing zesty release file

### ISSUE THREAD

**Issue by chris-roerig** [datto/dattobd#141]
I'm trying to install the `dlad` but the repository appears to be gone. The error message is:

```
The repository 'https://cpkg.datto.com/datto-deb/public/zesty zesty Release' does not have a Release file.
```

Have these files been moved?

**Comment by crawfxrd** [comment]
For Ubuntu, we only produce packages for LTS releases.

**Comment by nixomose** [comment]
and zesty is a silly name anyway. :-)
