### ISSUE TITLE
Store the number of changed blocks in the COW file

### ISSUE THREAD

**Issue by amorphina** [datto/dattobd#148]
Hi,

According to the documentation, the first 4096 bytes of the COW file contain some meta data.
Is is possible to include the number of changed blocks in this metadata and add a method of retrieving that information (maybe with dbdctl). This way based on some old numbers, one should be able to determine the time needed for a complete backup.

This could as well be extended and the update-img command can have a --progress option to show how many out of how many blocks are copied.
Example:
3761 out of 91828 blocks updated.

Kind Regards,
Atanas Stoyanov

**Comment by crawfxrd** [comment]
This is now available in the driver. `update-img` has not been updated to use it.

For the current snapshot/incremental set, the number of changed blocks is reported in `/proc/datto-info`. This can be used to estimate how much data will need to be copied before taking the snapshot.

For the purpose of an incremental backup, the value must be read from the COW header of the incremental file.
