### ISSUE TITLE
Filesystem on snapshot is not commited

### ISSUE THREAD

**Issue by uroni** [datto/dattobd#15]
Steps to reproduce (with dattobd 0.8.10, kernel 3.10.0-327.4.4.el7.x86_6): 

dbdctl setup-snapshot /dev/vda1 /.datto 0
mount /dev/datto0 /mnt/snap
EXT4-fs (datto0): INFO: recovery required on readonly filesystem
EXT4-fs (datto0): write access unavailable, cannot proceed

Expected: Filesystem on block device is mountable without "norecovery" flag, because it does not need recovery
Is: Dattobd does not flush the filesystem journal before creating the snapshot

You are already using freeze_bdev when the block device is transitioned from snapshot to tracing. Couldn't you call that during snapshot creation as well?

**Comment by tcaputi** [comment]
I believe there may be some confusion as to the terminology in the driver code. The 2 modes are 'snapshot' and 'incremental'. Both are represented by struct snap_device, and functions related to that struct start with tracer_. This is a leftover from when the snap_device struct only handled snapshots. In all honesty we should probably rename the struct to tracer to match the function calls. Functions that have to do with the struct in snapshot mode are prefixed with 'snap_' and functions that have to do with the struct in incremental mode are prefixed with 'inc_'.

We do call freeze_bdev() on creating a snapshot (see the call to __tracer_setup_tracing() in tracer_setup_active_snap()). This function does not require that the filesystem flushes the journal, only that the filesystem is in a consistent state. We cannot call a more drastic function (such as unmounting) because that would require the user to close all their open files on that device. 

During our tests on ext4 we use -o noload,noexec,ro and it mounts without complaining. When we copy the image off the only place we occasionally find corruption is within the COW file, which is to be expected since the COW file is the only mutable part of the snapshot.

**Comment by uroni** [comment]
You are right. I compared it with the lvm snapshotting which does not require norecovery/noload and did not notice that lvm creates writable snapshots per default.

A filesystem mounted with norecovery/noload is not suitable for backup (For ext4 see here: https://www.kernel.org/doc/Documentation/filesystems/ext4.txt ). I have solved this issue by putting a writable device mapper snapshot on top of the dattobd snapshot but that is not really an efficient solution I guess.

**Comment by tcaputi** [comment]
On the contrary, the filesystem is still suitable for backup as long as the (unsynced) journal is copied with the backup. The journal can then be replayed on the writable system where the backup is stored.

**Comment by uroni** [comment]
Yes, if it is a block-level backup and not a file-level backup, like I am trying to do (that is why I am mounting it in the first place).

**Comment by OmegaPhil** [comment]
Thanks for the device-mapper snapshot idea uroni - for others like me coming across this that want to do rsync backups off a clean root filesystem snapshot (and therefore at least writable for the mounting phase), the following works - device-mapper requires a dedicated COW device, I have got around this by creating a zRAM device (easy to do and properly documented), however supposedly 200MB of compressed RAM wasn't enough for an rsync backup (access time maybe??) so I fell back to a readonly mount, which presumably still cleans up the filesystem beforehand:

With a datto bd snapshot already set up to '/dev/datto0':

```
# Creation of zRAM device
sudo modprobe zram num_devices=1
sudo zramctl /dev/zram0 -s 100M

# Register the COW device (100MB in 512B blocks)
sudo dmsetup create os-volume-snapshot-cow --table '0 204800 linear /dev/zram0 0'

# Determine the number of 512B blocks present in '/dev/datto0' (exactly the same as the source volume BUT NOT the same as the number of blocks in the overlying filesystem)
lsblk -b /dev/datto0 | awk '(FNR == 2) { print $4 / 512 }'

# Register the origin device, replacing out '<number of blocks>'
sudo dmsetup create os-volume-snapshot-origin --table '0 <number of blocks> snapshot-origin /dev/datto0'

# Create the dmsetup snapshot device (note that 'snapshot' is a table thing, not a dmsetup command), replacing out '<number of blocks>'
sudo dmsetup create os-volume-snapshot --table '0 <number of blocks> snapshot /dev/mapper/os-volume-snapshot-origin /dev/mapper/os-volume-snapshot-cow N 8'

# Readonly mount of actual filesystem to '/media/os':
sudo mkdir '/media/os'
sudo mount -o ro /dev/mapper/os-volume-snapshot /media/os
```

And then tearing the device-mapper snapshot down:

```
sudo umount /dev/mapper/os-volume-snapshot
sudo dmsetup suspend os-volume-snapshot
sudo dmsetup remove os-volume-snapshot os-volume-snapshot-cow os-volume-snapshot-origin
sudo zramctl --reset /dev/zram0
sudo modprobe -r zram
```

I don't yet have a way of telling how much a zRAM device is used up (just getting complaints from device-mapper when its full), perhaps I could write a bitpattern before registering it if I was desperate, but so far the readonly mount has worked.

**Comment by tcaputi** [comment]
This is actually a very interesting idea. The original intent of this project was to enable block level incremental backups, but there seems to be demand for using it to do file based backups as well. Perhaps we can include a script similar to the one you posted above in the utils/ to make this easier for people.

**Comment by OmegaPhil** [comment]
Cool, I have made a gist with the script I use now (no changes except the license header, won't let me attach it directly): https://gist.github.com/OmegaPhil/7ae10aff93235b5428a4

Note this is the first time I've done anything serious with device-mapper, but this has 'worked' (i.e. no I/O failures reported) for 3 local systems and 1 remote one now.

**Comment by tcaputi** [comment]
@OmegaPhil Great! We'll have QA look at it and see if anything needs changing.

**Comment by crawfxrd** [comment]
I finally got some time to try the steps @OmegaPhil provided for rsync backups. I got it working for my ext4 volume without any problems. However, attempting it on an ext2 and an XFSv4 volume failed mounting the read-only dm snapshot. We'll be looking into getting it working and tested in all cases dattobd itself supports, so it will take some more time.

**Comment by ktosiek** [comment]
I've tried just mounting /dev/datt0 with ext4. The snapshot was taken while running pgbench. In dmesg I see:
```
[1051843.937738] EXT4-fs (datto0): write access unavailable, skipping orphan cleanup
[1051843.937743] EXT4-fs (datto0): recovery complete
[1051843.937745] EXT4-fs (datto0): mounted filesystem with ordered data mode. Opts: (null)
```
which looks like ext4 could somehow recover without write access to the device. Also, it looks like I can recover the database from that mounted datto0.

Can I depend on that behaviour I'm seeing?

**Comment by tcaputi** [comment]
This should be fine. this warning should be the result of deleted but still open files in use by the main disk. In the snapshot they appear to ext4 that they have been leaked.
