### ISSUE TITLE
Enhanced VM Support

### ISSUE THREAD

**Issue by dakami** [datto/dattobd#154]
So I've found an amusing use of dattobd:  Booting a VM from a snapshot of a running system. You get the existing config, but you can't break anything.  It's cute, and Linux (unlike Windows) instantly adapts to the VM hardware.

There are two points of complexity, which you may or may not be interested in addressing.  I handle both right now with various tricks in qemu.

One is, of course, that dattobd devices are read only.  No problem, qemu qcow2 devices can have backing files.  No problem, you give me one.

More of a problem is that you actually clone partitions, not block devices.  I understand this is because you are doing magic with the file systems in question, placing changes to the file system *in* the file system.  There's no FS to a block device, only to a partition, so there you go.

It's possible I'm misunderstanding, so let me know if I am!

However, what this means in practice is that I can't just boot off the parent dattobd drive directly.  I have to use qemu's support for launching a specific kernel with a specific initrd, and then mounting block devices from there, in order to function.  That's doable, and even helpful, but I'd prefer to just incept the entire host.

In effect, it would be helpful for dattobd to have a mode that cloned an entire block device, not just individual partitions within it.  I don't need you handling making the block device read/write but it would actually be helpful if you could merge its partitions.

If this interests you I can give you the sequence that boots a VM off of dattobd.  It's surprisingly useful for testing changes.

**Comment by dakami** [comment]
![image](https://user-images.githubusercontent.com/2106854/43442073-bacce842-9451-11e8-907c-c884ad63e853.png)
![image](https://user-images.githubusercontent.com/2106854/43442109-d44ab84e-9451-11e8-96f7-9241420faf0a.png)

**Comment by nixomose** [comment]
couldn't you just make a read-only loop device? Or use dm to make a snapshot of the device so it doesn't change?

**Comment by dakami** [comment]
From what I could tell, dm requires another drive, and if writes fail, all hell breaks loose *in the host*.  The interesting thing about dattobd is that the host (supposedly?) never fails.

**Comment by dakami** [comment]
(In other words, the factors that make dattobd interesting for backup, apply to this live VM snapshot case as well.)

**Comment by nixomose** [comment]
I'm not sure I see what you're getting at, but you can make a dm of a loop. So you should be able to make a read only loop of your device, make a dm out of it, take a snapshot of that and do an overlay thing on that.
Actually dm has its own overlay thing, I think it's called cow, something like that. I never tried this combination myself, but seems like it might work. There's the issue of the underlying disk changing on you, which is what dattobd gets you, but I think you should be able to use a dm snapshot to achieve the same effect? Now that I think about it, I'm not 100% sure because I can see dm relying on the underlying thing not changing for its snapshot. I haven't played with those features of dm in a while, but the features are there and might be worth checking out.
No doubt dattobd is a much lighter weight solution, but as you point out, only works on volumes, not entire block devices.

**Comment by dakami** [comment]
Sure, but these volumes contain block devices, and the relationship is available at this particular layer.  I'm wondering if it's interesting to try to jam the behavior in, or if there's a reason it's unjammable.

**Comment by nixomose** [comment]
it's doable, anything is doable, but it's not trivial and there's no point for our use case, but it's certainly doable.
The big picture problem is that the cow file has to go somewhere. Right now it goes to a file on the volume being snapshotted. If you change it to go somewhere else (another volume, memory, etc) you should be able to go after an entire block device not just a volume on the block device. But again, out of scope for our purposes.

**Comment by nixomose** [comment]
no, that'll all work, but it sure is a lot more work than just writing a script to do all the volumes one after the other. I have a feeling I'm missing what you're getting at. 
Couldn't you just create a sparse file the size of your physical disk, put it on a loop, fdisk a loop, create the partition table just like the original disk (or save yourself some effort and just dd the partition table from your disk to the loop or file directly) then snapshot all your volumes, then dd each volume to the correct location in the loop/file?
The end result will be one big file with a partition table with all your volumes and they'd all be there.
It's a bit of playing around to get all the partition locations, but that should work, nothing to change in dattobd, just a bunch of scripting.
