### ISSUE TITLE
Fedora 29 repo

### ISSUE THREAD

**Issue by ajtucker** [datto/dattobd#159]
Fedora 29 was released this week, but there's currently no repository for 29 here: https://cpkg.datto.com/datto-rpm/repoconfig/.

I've followed the manual install while running Fedora 29 and things appear to work ok. I've also tried `make rpm` and the packages appear to be created alright, though I've not tried an install as the resulting versions (e.g. dkms-dattobd-0.10.7-1.fc29.noarch) are deemed to be older than the old versions currently installed (e.g. dkms-dattobd-0.10.7-21.1.fc28.noarch).

**Comment by crawfxrd** [comment]
I'd like to address #158 before releasing for Fedora 29. And after some more testing, I may need to readdress #40.

**Comment by Conan-Kudo** [comment]
Fedora 29 packages have been released now.

**Comment by ajtucker** [comment]
Thanks, that works a treat!
