### ISSUE TITLE
fix strncpy problem

### ISSUE THREAD

**Issue by nixomose** [datto/dattobd#162]
this is in my list of things to do that I'm realistically never going to get to, so I wanted to at least write it down here so it doesn't get lost.

the strncpys are not safe if the source string is longer than the max length it doesn't add a \0 string terminator and everything go boom.

ll_pathname[pathname1_len + need_leading_slash + pathname2_len] = '\0';
 1389 
 1390         strncpy(full_pathname, pathname1, pathname1_len);
 1391         if(need_leading_slash) full_pathname[pathname1_len] = '/';
 1392 //      xxxz
 1393         strncpy(full_pathname + pathname1_len + need_leading_slash, pathname2, pathname2_len);
 1394 
 1395         *path_out = full_pathn

**Comment by crawfxrd** [comment]
These should have be resolved with 6d555ad7ee16926a0282f88e99db5e04229940f1 when we starting using a version of GCC with `stringop-truncation` warnings enabled.

In `pathname_concat`, an extra byte is allocated in the destination string to ensure it will be `NULL` terminated.
https://github.com/datto/dattobd/blob/e3e6a3b76804d40ca526cd66c6b54e6fc0ad50f9/src/dattobd.c#L1385

**Comment by nixomose** [comment]
cool, then it's all taken care of, thanks.
