### ISSUE TITLE
'failed to locate system call table, persistence disabled' on load of kernel module

### ISSUE THREAD

**Issue by OmegaPhil** [datto/dattobd#17]
Debian Testing here, kernel 4.3.3 64bit - on insmoding the v0.8.14 module I get the following kernel message:

```datto: failed to locate system call table, persistence disabled```

This doesn't appear to disturb my ability to use the created snapshot device file though (haven't played with incremental mode, I'm just interested in getting a full snapshot, backing it up and then rmmoding).

**Comment by tcaputi** [comment]
If that is all you need, then you can ignore that warning. The feature that is being disabled is the ability to maintain a snapshot even if you unmount the volume. With persistence disabled, attempting to unmount the volume while a snapshot (or incremental) is active will result in the OS telling you that the volume is busy and can't be unmounted.

**Comment by OmegaPhil** [comment]
Thanks, thats a very posh feature.

**Comment by tcaputi** [comment]
No problem. We could probably reword that warning to be clearer about what it does.
