### ISSUE TITLE
get_task_io_context() unexported in Linux 5.0

### ISSUE THREAD

**Issue by crawfxrd** [datto/dattobd#178]
`get_task_io_context()` was unexported in 5.0. We find the definition in the header, but can't use the symbol.

ref: [b6676f653f13](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit?id=b6676f653f13f83582985bc713525a48d735b2a3) ("block: remove a few unused exports")

```
$ uname -r
5.0.4-200.fc29.x86_64
$ insmod ./src/dattobd.ko 
insmod: ERROR: could not insert module ./src/dattobd.ko: Unknown symbol in module
$ dmesg
[ 2128.183027] dattobd: Unknown symbol get_task_io_context (err -2)
```

**Comment by nixomose** [comment]
well that's annoying.
