### ISSUE TITLE
img-merge: command not found

### ISSUE THREAD

**Issue by Prajithp** [datto/dattobd#18]
Could you please confirm, from where I can install img-merge command? I could not find this command in both centos and ubuntu.

**Comment by Conan-Kudo** [comment]
Hello @Prajithp,

Thank you for trying out dattobd. As it turns out, our Makefile doesn't install img-merge, even though it would compile it. We provide this in the dattobd-utils package from our repository because we're manually compiling it, but we will certainly address this ASAP.

**Comment by tcaputi** [comment]
fixed in merge #20.
