### ISSUE TITLE
dattobd-dkms deb fails to install with kernel 5.0.0

### ISSUE THREAD

**Issue by keleuk** [datto/dattobd#189]
I'm attempting to install the dattobd packages to my Ubuntu Bionic system.
I'm running kernel version 5.0.0-20 (x86_64).
After adding the datto repository, when I try to install dattobd-dkms and dattobd-utils, it fails while building the kernel module.

Here is my make.log:
[make.log](https://github.com/datto/dattobd/files/3399742/make.log)

**Comment by crawfxrd** [comment]
We do not have a release that supports 5.0+ yet.

**Comment by dark4rest** [comment]
Fedora server 30 do not supported?

**Comment by yves84** [comment]
Same error here... Ubuntu Bionic Kernel 5.0.0-23 (x86_64)...

**Comment by crawfxrd** [comment]
@Conan-Kudo @dakotarwilliams @tcaputi This issue can be closed.

**Comment by dakotarwilliams** [comment]
Fixed in #182

**Comment by Conan-Kudo** [comment]
@dakotarwilliams We don't have the packages published yet, though?

**Comment by dakotarwilliams** [comment]
So? The issue has been fixed. Closing issues when they're fixed doesn't let issues pile up if we forget to close them when a package is published. Also, if there is a fix made, why keep the issue around to potentially confuse people that it's not fixed yet?
