### ISSUE TITLE
OS down after taking a snapshot.

### ISSUE THREAD

**Issue by yito24** [datto/dattobd#197]
OS:RHEL7.5
Kernel:3.10.0-862.14.4.el7.x86_64

OS down immediately after taking a snapshot.
This is a very rare symptom.
There is no dump.

Do you have any past cases?

**Comment by Conan-Kudo** [comment]
Could you turn on kdumps and try to reproduce it? There isn't enough information here to do anything right now, and we've never observed this problem before.

**Comment by yito24** [comment]
Thanks for your comment.
I will collect dump when it occurs next time.
I will contact you again at that time.

Thanks.
