### ISSUE TITLE
Snapshotting and open files

### ISSUE THREAD

**Issue by octabrain** [datto/dattobd#2]
How do you deal with files whose writes are in process and a snapshot command is issued.

I had faced this issues, since if the file whose writes are still in process, the final ext3/4 headers of the new blocks numbers and new size are written after all the block level data writes are completed. If snapshot command is issued in between it will corrupt the file system if its not handled correctly.

**Comment by tcaputi** [comment]
we freeze the filesystem (very briefly) at the time of snapshotting. This will put the filesystem into a consistent state before we take the snapshot.
