### ISSUE TITLE
 Snapshot creation problem linux centos-7

### ISSUE THREAD

**Issue by yingzhoujie** [datto/dattobd#203]
[root@localhost dattobd]# dbdctl setup-snapshot /dev/sda1 /.datto 0
driver returned an error performing specified action. check dmesg for more info: Invalid argument

dmesg

[ 1391.331992] dattobd: loading out-of-tree module taints kernel.
[ 1391.332256] dattobd: module verification failed: signature and/or required key missing - tainting kernel
[ 1410.928474] datto: '/.datto' is not on 'sda1': -22
[ 1410.928478] datto: error setting up cow manager: -22
[ 1410.928489] datto: error setting up tracer as active snapshot: -22
[ 1410.928492] datto: error during setup ioctl handler: -22
[ 1423.210085] datto: '/.datto' is not on 'sda1': -22
[ 1423.210089] datto: error setting up cow manager: -22
[ 1423.210104] datto: error setting up tracer as active snapshot: -22
[ 1423.210108] datto: error during setup ioctl handler: -22
[ 1871.791509] datto: '/.datto' is not on 'sda1': -22
[ 1871.791514] datto: error setting up cow manager: -22
[ 1871.791526] datto: error setting up tracer as active snapshot: -22
[ 1871.791529] datto: error during setup ioctl handler: -22
[ 2801.437176] datto: error creating/opening file '/var/backup/datto' - -2: -2
[ 2801.437180] datto: error opening file: -2
[ 2801.437182] datto: error during cow manager initialization: -2
[ 2801.437185] datto: error setting up cow manager: -2
[ 2801.437187] datto: error setting up tracer as active snapshot: -2
[ 2801.437191] datto: error during setup ioctl handler: -2
[ 2845.493962] datto: '/var/backup/datto' is not on 'sda1': -22
[ 2845.493967] datto: error setting up cow manager: -22
[ 2845.493978] datto: error setting up tracer as active snapshot: -22
[ 2845.493981] datto: error during setup ioctl handler: -22
[ 2887.494115] datto: error creating/opening file '/var/backup/datto' - -21: -21
[ 2887.494118] datto: error opening file: -21
[ 2887.494119] datto: error during cow manager initialization: -21
[ 2887.494121] datto: error setting up cow manager: -21
[ 2887.494122] datto: error setting up tracer as active snapshot: -21
[ 2887.494123] datto: error during setup ioctl handler: -21
[ 2897.108504] datto: '/var/backup/datto' is not on 'sda1': -22
[ 2897.108508] datto: error setting up cow manager: -22
[ 2897.108519] datto: error setting up tracer as active snapshot: -22
[ 2897.108523] datto: error during setup ioctl handler: -22
[ 2908.491704] datto: '/var/backup/datto' is not on 'sda1': -22
[ 2908.491708] datto: error setting up cow manager: -22
[ 2908.491718] datto: error setting up tracer as active snapshot: -22
[ 2908.491721] datto: error during setup ioctl handler: -22
[ 3014.897575] datto: '/var/backup/datto' is not on 'sda1': -22
[ 3014.897579] datto: error setting up cow manager: -22
[ 3014.897589] datto: error setting up tracer as active snapshot: -22
[ 3014.897591] datto: error during setup ioctl handler: -22
[ 3197.961576] datto: error during setup ioctl handler: -2
[ 3807.859327] datto: error during setup ioctl handler: -2
[ 3816.415668] datto: '/.datto' is not on 'sda1': -22
[ 3816.415672] datto: error setting up cow manager: -22
[ 3816.415683] datto: error setting up tracer as active snapshot: -22
[ 3816.415686] datto: error during setup ioctl handler: -22
[ 3831.220646] datto: error during setup ioctl handler: -15
[ 3866.963317] datto: error during setup ioctl handler: -15
[ 3872.502385] datto: '/.datto' is not on 'sda1': -22
[ 3872.502388] datto: error setting up cow manager: -22
[ 3872.502397] datto: error setting up tracer as active snapshot: -22
[ 3872.502400] datto: error during setup ioctl handler: -22

[root@localhost dattobd]# df -h
Filesystem               Size  Used Avail Use% Mounted on
devtmpfs                 470M     0  470M   0% /dev
tmpfs                    487M     0  487M   0% /dev/shm
tmpfs                    487M  8.5M  478M   2% /run
tmpfs                    487M     0  487M   0% /sys/fs/cgroup
/dev/mapper/centos-root   17G  4.6G   13G  27% /
/dev/sda1               1014M  154M  861M  16% /boot
tmpfs                     98M   72K   98M   1% /run/user/0

[root@localhost dattobd]# blkid
/dev/mapper/centos-root: UUID="cd0d30bf-5bbd-46f3-b076-014811be5351" TYPE="xfs" 
/dev/sda2: UUID="Memd0u-cz7M-PUml-0um1-mAv0-gEy0-CmdE47" TYPE="LVM2_member" 
/dev/sda1: UUID="a324b828-a926-4c4a-a0ec-ccca7dfcbbe6" TYPE="xfs" 
/dev/mapper/centos-swap: UUID="4859267f-ff4a-4468-82a6-4f1f1a8f76e6" TYPE="swap" 

[root@localhost dattobd]# uname -r
3.10.0-1062.el7.x86_64

**Comment by crawfxrd** [comment]
```
dbdctl setup-snapshot /dev/sda1 /.datto 0
```
The error in dmesg tells you what is wrong:
```
datto: '/.datto' is not on 'sda1': -22
```

`/dev/sda1` is `/boot`. The backing file must exists on this device. e.g.,

```
dbdctl setup-snapshot /dev/sda1 /boot/.datto 0
```

**Comment by yingzhoujie** [comment]
What is a snapshot
is /.datto ？ /dev/sda1  ?    /dev/datto0?
