### ISSUE TITLE
 Snapshot cannot be mounted

### ISSUE THREAD

**Issue by yzj0911** [datto/dattobd#205]
Snapshot cannot be mounted ？

[root@localhost ~]# dbdctl setup-snapshot /dev/sda1  /boot/.datto 0
[root@localhost ~]# mount /dev/datto0 /mnt
mount: /dev/datto0 is write-protected, mounting read-only
mount: wrong fs type, bad option, bad superblock on /dev/datto0,
       missing codepage or helper program, or other error
       In some cases useful info is found in syslog - try
       dmesg | tail or so.

[ 9097.028342] XFS (datto0): Filesystem has duplicate UUID a324b828-a926-4c4a-a0ec-ccca7dfcbbe6 - can't mount

**Comment by crawfxrd** [comment]
XFS requires the `nouuid` option when mounting clones.
 
```
mount -o ro,norecovery,nouuid /dev/datto0 /mnt
```
