### ISSUE TITLE
No repo for eoan of ubuntu

### ISSUE THREAD

**Issue by bvandorf** [datto/dattobd#220]
The repository 'https://cpkg.datto.com/datto-deb/public/ubuntu eoan Release' does not have a Release file.

**Comment by Conan-Kudo** [comment]
Per our [installation documentation](https://github.com/datto/dattobd/blob/master/INSTALL.md), we only offer packages for Ubuntu LTS releases. We intend to offer Ubuntu 20.04 packages shortly.
