### ISSUE TITLE
Compilation too much fails on kernel 2.6.18

### ISSUE THREAD

**Issue by oracleloyall** [datto/dattobd#222]
/home/test/dattobd-master/src/dattobd.c:124: error: redefinition of typedef ‘fmode_t’
include/linux/types.h:185: error: previous declaration of ‘fmode_t’ was here
/home/test/dattobd-master/src/dattobd.c: In function ‘blkdev_get_by_path’:
/home/test/dattobd-master/src/dattobd.c:185: error: too many arguments to function ‘blkdev_put’
/home/test/dattobd-master/src/dattobd.c: In function ‘submit_bio_wait’:
/home/test/dattobd-master/src/dattobd.c:345: warning: assignment from incompatible pointer type
/home/test/dattobd-master/src/dattobd.c: In function ‘dattobd_bio_endio’:
/home/test/dattobd-master/src/dattobd.c:359: error: too few arguments to function ‘bio_endio’
/home/test/dattobd-master/src/dattobd.c: At top level:
/home/test/dattobd-master/src/dattobd.c:584: error: static declaration of ‘proc_create’ follows non-static declaration
include/linux/proc_fs.h:129: error: previous declaration of ‘proc_create’ was here
/home/test/dattobd-master/src/dattobd.c: In function ‘dattobd_bio_get_queue’:
/home/test/dattobd-master/src/dattobd.c:638: error: ‘struct bio’ has no member named ‘bi_disk’
/home/test/dattobd-master/src/dattobd.c: In function ‘dattobd_bio_set_dev’:
/home/test/dattobd-master/src/dattobd.c:647: error: implicit declaration of function ‘bio_set_dev’
/home/test/dattobd-master/src/dattobd.c: In function ‘dattobd_bio_copy_dev’:
/home/test/dattobd-master/src/dattobd.c:656: error: implicit declaration of function ‘bio_copy_dev’
/home/test/dattobd-master/src/dattobd.c: At top level:
/home/test/dattobd-master/src/dattobd.c:896: warning: initialization from incompatible pointer type
/home/test/dattobd-master/src/dattobd.c:897: warning: initialization from incompatible pointer type
/home/test/dattobd-master/src/dattobd.c: In function ‘dattobd_do_truncate’:
/home/test/dattobd-master/src/dattobd.c:1491: error: too many arguments to function ‘notify_change’
/home/test/dattobd-master/src/dattobd.c: In function ‘__file_unlink’:
/home/test/dattobd-master/src/dattobd.c:1666: error: too many arguments to function ‘vfs_unlink’
/home/test/dattobd-master/src/dattobd.c: In function ‘bio_make_read_clone’:
/home/test/dattobd-master/src/dattobd.c:2482: warning: assignment from incompatible pointer type
/home/test/dattobd-master/src/dattobd.c: At top level:
/home/test/dattobd-master/src/dattobd.c:3078: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘tracing_mrf’
/home/test/dattobd-master/src/dattobd.c:3110: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘snap_mrf’
/home/test/dattobd-master/src/dattobd.c: In function ‘find_orig_mrf’:
/home/test/dattobd-master/src/dattobd.c:3172: error: ‘tracing_mrf’ undeclared (first use in this function)
/home/test/dattobd-master/src/dattobd.c:3172: error: (Each undeclared identifier is reported only once
/home/test/dattobd-master/src/dattobd.c:3172: error: for each function it appears in.)
/home/test/dattobd-master/src/dattobd.c: In function ‘__tracer_should_reset_mrf’:
/home/test/dattobd-master/src/dattobd.c:3194: error: ‘tracing_mrf’ undeclared (first use in this function)
/home/test/dattobd-master/src/dattobd.c: In function ‘__tracer_destroy_base_dev’:
/home/test/dattobd-master/src/dattobd.c:3314: error: too many arguments to function ‘blkdev_put’
/home/test/dattobd-master/src/dattobd.c: In function ‘__tracer_bioset_init’:
/home/test/dattobd-master/src/dattobd.c:3555: error: too few arguments to function ‘bioset_create’
/home/test/dattobd-master/src/dattobd.c: In function ‘__tracer_setup_snap’:
/home/test/dattobd-master/src/dattobd.c:3583: error: ‘snap_mrf’ undeclared (first use in this function)
/home/test/dattobd-master/src/dattobd.c:3610: warning: assignment discards qualifiers from pointer target type
/home/test/dattobd-master/src/dattobd.c: In function ‘__tracer_setup_tracing’:
/home/test/dattobd-master/src/dattobd.c:3744: error: ‘tracing_mrf’ undeclared (first use in this function)
/home/test/dattobd-master/src/dattobd.c: In function ‘__verify_bdev_writable’:
/home/test/dattobd-master/src/dattobd.c:4057: error: too many arguments to function ‘blkdev_put’
/home/test/dattobd-master/src/dattobd.c: In function ‘__handle_bdev_mount_writable’:
/home/test/dattobd-master/src/dattobd.c:4657: error: too many arguments to function ‘blkdev_put’
/home/test/dattobd-master/src/dattobd.c:4664: error: too many arguments to function ‘blkdev_put’
/home/test/dattobd-master/src/dattobd.c: In function ‘post_umount_check’:
/home/test/dattobd-master/src/dattobd.c:4747: error: too many arguments to function ‘blkdev_put’

**Comment by crawfxrd** [comment]
Your `kernel-config.h` was not generated correctly.

**Comment by oracleloyall** [comment]
What dependency configuration is required? Can you give me some instructions?

**Comment by oracleloyall** [comment]
> Your `kernel-config.h` was not generated correctly.

What dependency configuration is required? Can you give me some instructions?

**Comment by crawfxrd** [comment]
Do you have the headers for your kernel installed? That's usually the cause for this.
