### ISSUE TITLE
datto_snap_cow0 consuming 100% CPU

### ISSUE THREAD

**Issue by gusarg81** [datto/dattobd#223]
Hi,

There is a process, with that name, consuming one core of my server to 100% and I can't kill it by any means.

My OS: ubuntu 18.04, using dattobd from repository (version 0.10.13-27)

Any ideas how Can I stop it (without restarting my server). And also why this could happen?

Thanks in advance.

**Comment by gusarg81** [comment]
Hi,

   I found second server where I have installed dattobd (which I use everywhere with UrBackup) and is consuming 100% cpu as well (same OS, same kernel, which is 5.3.x).

Also this is a problem since I can' t kill the process (datto_snap_cow0) and restarting the server cause a hang, so I have to manually poweroff and on.

This was not happening before (or at least, not in older kernels).

**Comment by kiwy42** [comment]
I have similar issue using Urbackup on an Ubuntu 20.04 kernel 5.4.0-100 and dattodb 0.10.15-29.1ubuntu20.04.
On a regular basis but without a clear pattern dattodb just hang consumming 100% forcing a hard reboot on the server and a full reinstallation of dattodb to insure that backup recovers.

**Comment by nickchen-cpu** [comment]
Hi @kiwy42 
Did you use raid1 or raid5 ?

**Comment by nickchen-cpu** [comment]
Hi @kiwy42 
Kernel 5.0 seems fine with raid 1, you can give it a try.

**Comment by Swistusmen** [comment]
Hello, I belive this has been fixed with commit 2ad52cb2f0cf8c347083ca84254e89908385ff9e, regarding this, I'm closing this issue. You can check it out, in case it will still not work, please reopen
