### ISSUE TITLE
Filesystem remounted RO after taking snapshot

### ISSUE THREAD

**Issue by marco-jem** [datto/dattobd#225]
Hi guys!

I'm trying to make a backup of a ranning server using Datto, but as soon as I create a snapshot of the (root) filesystem the filesystem itself gets remounted in RO mode due to errors.

Command used to take snapshot:
root@debian-16gb-nbg1-1 ~ # dbdctl setup-snapshot /dev/sda1 /.datto 0

Datto was installed from your repo of debian packages and compiled with DKMS.

The dmesg output is in the attached file and there is also the output of "ohai" software which describes the system in amazing details.

Here is a brief description of the system:

## Hardware description
Virtual machine hosted at Hetzner.de

## OS version
root@debian-16gb-nbg1-1 ~ # lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.9 (stretch)
Release:	9.9
Codename:	stretch

## Kernel version
root@debian-16gb-nbg1-1 ~ # uname -r
4.9.0-12-amd64

## Installed kernel headers packages
linux-headers-4.9.0-12-amd64
inux-headers-4.9.0-12-common
linux-headers-amd64

## DKMS
root@debian-16gb-nbg1-1 ~ # dkms status
dattobd, 0.10.13, 4.9.0-12-amd64, x86_64: installed

## Datto Repository
root@debian-16gb-nbg1-1 ~ # cat /etc/apt/sources.list.d/datto-linux-agent.list 
deb [arch=amd64] https://cpkg.datto.com/datto-deb/public/stretch stretch main

## Attachments
[datto_dmesg.txt](https://github.com/datto/dattobd/files/4889219/datto_dmesg.txt)
[datto_sysinfo.txt](https://github.com/datto/dattobd/files/4889220/datto_sysinfo.txt)

**Comment by dakotarwilliams** [comment]
Known, #224 will be merged soon to resolve this issue.
