### ISSUE TITLE
dattodb repo for ubuntu focal isn't working properly

### ISSUE THREAD

**Issue by ptempier** [datto/dattobd#226]
Hello

When i try to install dattodb following the instructions, the repo does not appear to work properly

sudo apt-get update
The repository 'https://cpkg.datto.com/datto-deb/public/focal focal Release' does not have a Release file.

curl "https://cpkg.datto.com/datto-deb/public/focal"
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by itlists** [comment]
Same error here as well

**Comment by dakotarwilliams** [comment]
Official packages for focal have not yet been made due to known bugs with dattobd on kernels 5.3 and newer. Expect 0.10.14 to support focal.

**Comment by Conan-Kudo** [comment]
This has now been released with dattobd 0.10.14.
