### ISSUE TITLE
how to create snapshot by dattodb

### ISSUE THREAD

**Issue by nguyennv94** [datto/dattobd#227]
Hi everyone, i'm newbie, i have installed dattodb and urbackup client on centOS. I want to create snapshot and combine with urbackup, what should I do? thanks
Urbackup server: 2.4.12, urbackup client: 2.4.10.

Centos 7
#dbdctl setup-snapshot /dev/sda1 /mnt/
driver does not appear to be loaded: Invalid argument

#/usr/local/share/urbackup/dattobd_create_filesystem_snapshot
Cannot get device for filesystem

#dkms status
dattobd, 0.10.13: added

**Comment by dakotarwilliams** [comment]
It's added to dkms, but is the module loaded? `lsmod | grep dattobd`. If not, you could just run `dkms install -m dattobd/0.10.13`.

You'll also need to specify a minor number for `setup-snapshot`, the man page for dbdctl should have some info. Idk what urbackup is doing, but if it works the way I think it does, I think you shouldn't need to manually make a snapshot.

**Comment by nguyennv94** [comment]
> 
> 
> It's added to dkms, but is the module loaded? `lsmod | grep dattobd`. If not, you could just run `dkms install -m dattobd/0.10.13`.
> 
> You'll also need to specify a minor number for `setup-snapshot`, the man page for dbdctl should have some info. Idk what urbackup is doing, but if it works the way I think it does, I think you shouldn't need to manually make a snapshot.

Thanks
