### ISSUE TITLE
Ubuntu 20.04 Repo

### ISSUE THREAD

**Issue by ISSchuster** [datto/dattobd#228]
Hi, any news regarding Ubuntu 20.04 Repos?

I found an entry from April which said "We intend to offer Ubuntu 20.04 packages shortly."

It's August now ;-)

Ign:5 https://cpkg.datto.com/datto-deb/public/focal focal InRelease
Err:6 https://cpkg.datto.com/datto-deb/public/focal focal Release
  404  Not Found [IP: 8.34.181.206 443]

**Comment by wechsler42** [comment]
... and now it is September ;-)
... and I face the same error on Kubuntu 20.04.
Could you please prepare the Ubuntu20.04 packages soon.
TIA

**Comment by dakotarwilliams** [comment]
There is a known issue affecting kernel 5.3 and newer. When that issue has been addressed (which has been in #232, and is waiting on internal processes to be merged), we will make a release officially supporting those distros. Packages would be made for that new tag.

That aside, this is a code repository. Package repositories are provided as a courtesy. Code contributions are welcome. First party MRs, fixes, and updates are subject to planning within the team. We have more on our plate than just dattobd.

**Comment by DrRSatzteil** [comment]
Packages are now available in Focal repos.

**Comment by Conan-Kudo** [comment]
This has now been released with dattobd 0.10.14.
