### ISSUE TITLE
sendfile()?

### ISSUE THREAD

**Issue by victorstewart** [datto/dattobd#237]
once I create the COW file, I'd like to transfer it over a TCP connection rather than for example pipe `dd` into `ssh`. 

but am I correct that `sendfile()` will not work because the COW file is a block file? so i'd have to read/write it to the socket? essentially my only aim here is to copy a logical volume over the network. 

don't have any of my dev hardware with me so can't actually test this for a few weeks, hence the question!

**Comment by nixomose** [comment]
erm, you don't want to play with the cow file. the cow file is the interim temporary holding area for changes while maintaining the snapshot device.
what you want to do (I think) is copy the snapshot device, and that, yes, is a block device.
you could dd it to netcat or something like that.
but you'd be dding the entire block device.

**Comment by nixomose** [comment]
reading again, I'm getting the impression that you think the cow file is the delta between the last snapshot and the current one?
well, sorta, but not exactly.
it keeps track of the list of blocks that have changed, but it does not contain the data stored in those blocks.
so if you were planning on trying to sendfile just the deltas of changed data to accumulate a list of incrementals, that's not going to work.

**Comment by victorstewart** [comment]
ohhhhh i see! ya when i read the STRUCTURE doc, i was like wait how will the blocks be read if this is the file structure? lol.

essentially i'm just trying to get a frozen in time view of the block device, so that i can compress and copy/transfer it's data over the network. orchestrated from a C++ application.

**Comment by nixomose** [comment]
that, is exactly what it does do, but that frozen view is in the block device that dattobd makes (/dev/dattobd0 or whatever it's called)
if you look at the sample https://github.com/datto/dattobd/blob/master/utils/update-img.c

you can see what's available and how to use it.

**Comment by victorstewart** [comment]
ahh i see. all makes sense now. thanks so much!
