### ISSUE TITLE
Can I pre-allocate COW file smaller than ```cm->file_max``` initially then extend it only when new COW I/O comes?

### ISSUE THREAD

**Issue by nickchen-cpu** [datto/dattobd#245]
Hi, thanks for sharing Dattobd driver, it’s the best live snapshot software I've ever seen.
Can I assign the original size for the COW file which is much smaller than ```cm->file_max``` when creating the COW file?
I'd like to pre-allocate a small enough size(header + cow section), then extend it only when a new COW I/O comes in order to **reduce the latency of creating very large COW file at the beginning of the snapshot mode(where COW file may be over 100GB in some system so such creation would take over hours)**.
I mean: 
``` ret = file_allocate(cm->filp, 0, file_max);```
becomes
 ```ret = file_allocate(cm->filp, 0, cm->data_offset);```

![image](https://user-images.githubusercontent.com/70849044/104798268-378a8000-5800-11eb-8b22-fb14cba0536a.png)

I think this approach works because ```file_write``` will append(grow) the COW file once the write offset is larger than the current size of COW file, at the mean time appending to the COW file does not incur another COW I/O(same inode), so this change seems not to disturb the overall behaviors of I/Os during snapshot mode.

I believe the reason why Dattobd pre-allocate COW file in a specific size at the beginning of snapshot mode is as follows:

1. Reduce the sector fragmentation
2. Avoid 100% space used, which would cause system to hang
3. ext4 or better filesystem which support ```fallocate``` will call ```fallocate```  to get a chunk of free space only once

And once we do such dynamic COW file allocation, we're concerned about the following:

* Is free space enough? What size should ```cm->file_max``` be?
* How do we dynamically modify the contents of ```/proc/datto-info``` and COW header.
* After dd, the target image(say, ```dd of=/backup_sda```) only sees the original size of COW file , but it actually did contains all blocks of  COW file including the increased one(Because the source COW file's inode was snapshoted at the beginning of the snapshot mode, target image's inode only see the original size of COW file.).
* If we ```rm file.txt```(i.e., ```unlink``` the **data block**) during dynamic allocation snapshot mode, the **data block** is just unlinked but is not  COWed, So if we append COW file whose I/O also overwrites that **unlinked data block**, this block will be overwritten by COW file which causes data inconsistency between source and target.(Because appending I/O has the same inode with COW file itself so no another COW I/O happens)
![](https://i.imgur.com/D4rf5MB.png)
Does this statement make sense?
```
static int __cow_write_data(struct cow_manager *cm, void *buf){
        ...
        /* I want COW file to grow only when new COW I/O comes */
        ret = file_write(cm->filp, buf, curr_size, COW_BLOCK_SIZE);
        ...
}

```

**Comment by dakotarwilliams** [comment]
As far as the reasons for pre-allocation goes, you've pretty much hit the nail on the head.

The main issue with dynamic allocation for the COW file is updating which blocks on disk are now used by the COW file. Otherwise, new writes will be written to the COW file which would trigger another write that would then get written to the COW file, and so on and so forth, creating a infinite loop hanging your system until your disk fills up. Polling the filesystem to see which block(s) the new fragment is using after extension would be the only way to keep track of that sort of thing, which would severely hamper I/O performance (it's not great to begin with). We favored I/O performance during the design, so if you're planning to implement something like this, you'd need to provide an option to choose between static and dynamic allocation.

**Comment by nickchen-cpu** [comment]
Hi, @dakotarwilliams 
Thanks for replying.
I'm planning to implement Dynamic allocation, I will continue designing , Thanks.

Nick

**Comment by nickchen-cpu** [comment]
Hi, @dakotarwilliams .
There's another problem I want to ask regarding data consistency:
![](https://i.imgur.com/vYzGgVq.png)
Suppose we want to take snapshots for multiple partitions, e.g.,  **backing up a whole disk containing several partitions**. We ask Dattobd to first allocates COW files in the order of sda1, sda2 and sda3, and that's the problem: Snapshots were taken but **not at the same time**. For example: If **sda1** and **sda2**  take only some seconds to allocate COW files but **sda3**  take over several minutes to create the one, is it possible that the disk in target machine have some data consistency issues.

step1:
![](https://i.imgur.com/dqpS8M8.png)
It takes **1 second** to allocate COW in sda1.
step2:
![](https://i.imgur.com/iIokCJ6.png)
It takes **5 seconds** to allocate COW in sda2.
step3:
![](https://i.imgur.com/qX3CLfN.png)
It takes **90 seconds** to allocate COW in sda3, if we modify some content on **sda3** during this creation of COW, because snapshot is not yet taken, the target machine will have the modified sda3 instead of the original sda3. Moreover, if sda3 record additional data on sda1 or sda2 during creating the COW file, it may cause the disastrous problems, that is, data consistency.

To overcome this problem, I defer the progress of ```tracing_mrf```, All tracing thread will wait until all COW files created.
```
struct setup_params{
        char *bdev; //name of block device to snapshot
        char *cow; //name of cow file for snapshot
        unsigned long fallocated_space; //space allocated to the cow file (in megabytes)
        unsigned long cache_size; //maximum cache size (in bytes)
        unsigned int minor; //requested minor number of the device
};
/*Collecting all setup_params*/
struct setup_params_group{
        unsigned int count;
        struct setup_params setup_params[];
};
```
The biggest difference from ```__ioctl_setup``` is that we split the **pre-allocation** and **tracing process**. Also we use ```count``` to loop all device.
```
static int __ioctl_setup_group(unsigned int *minors, char **bdev_paths, char **cow_paths, unsigned long *fallocated_spaces, unsigned long *cache_sizes, int count, int is_snap, int is_reload){
        int ret;
        int is_mounted[count];
        /*array of pointers*/
        struct snap_device *devs[count];

        unsigned int i;
        for(i = 0; i < count ; ++i){
                devs[i] = NULL;
        }
        for(i = 0; i < count ; ++i){
                //verify that the minor number is valid
                ret = verify_minor_available(minors[i]);
                if(ret) goto error;
                //check if block device is mounted
                ret = __verify_bdev_writable(bdev_paths[i], &is_mounted[i]);
                if(ret) goto error;
                //check that reload / setup command matches current mount state
                if(is_mounted[i] && is_reload){
                        ret = -EINVAL;
                        LOG_ERROR(ret, "illegal to perform reload while mounted");
                        goto error;
                }else if(!is_mounted[i] && !is_reload){
                        ret = -EINVAL;
                        LOG_ERROR(ret, "illegal to perform setup while unmounted");
                        goto error;
                }
                //allocate the tracing struct
                ret = tracer_alloc(devs+i);
                if(ret) goto error;

                //route to the appropriate setup function
                if(is_snap){
                        if(is_mounted[i]) {
                                ret = tracer_setup_active_snap_group(devs[i], minors[i], bdev_paths[i], cow_paths[i], fallocated_spaces[i], cache_sizes[i]);
                        }
                        else ret = tracer_setup_unverified_snap(devs[i], minors[i], bdev_paths[i], cow_paths[i], cache_sizes[i]);
                }else{
                        if(!is_mounted[i]) ret = tracer_setup_unverified_inc(devs[i], minors[i], bdev_paths[i], cow_paths[i], cache_sizes[i]);
                        else{
                                ret = -EINVAL;
                                LOG_ERROR(ret, "illegal to setup as active incremental");
                                goto error;
                        }
                }
                if(ret) goto error;
        }
        if(is_snap){
                for(i = 0 ; i < count ; ++i){
                        if(is_mounted[i]){
                                ret = wait_cow_completion(devs[i], minors[i]);
                        }
                        if(ret) goto error;
                }
        }

        return 0;

error:
        LOG_ERROR(ret, "error during setup ioctl handler");
        for(i = 0; i < count ; ++i)
                if(devs[i])
                        kfree(devs[i]);
        return ret;
}

```
**Pre-allocation**
```
static int tracer_setup_active_snap_group(struct snap_device *dev, unsigned int minor, const char *bdev_path, const char *cow_path, unsigned long fallocated_space, unsigned long cache_size){
        int ret;

        set_bit(SNAPSHOT, &dev->sd_state);
        set_bit(ACTIVE, &dev->sd_state);
        clear_bit(UNVERIFIED, &dev->sd_state);

        //setup base device
        ret = __tracer_setup_base_dev(dev, bdev_path);
        if(ret) goto error;

        //setup the cow manager
        ret = __tracer_setup_cow_new(dev, dev->sd_base_dev, cow_path, dev->sd_size, fallocated_space, cache_size, NULL, 1);
        if(ret) goto error;

        //setup the cow path
        ret = __tracer_setup_cow_path(dev, dev->sd_cow->filp);
        if(ret) goto error;

        //setup the snapshot values
        ret = __tracer_setup_snap(dev, minor, dev->sd_base_dev, dev->sd_size);
        if(ret) goto error;

        //setup the cow thread and run it
        ret = __tracer_setup_snap_cow_thread(dev, minor);
        if(ret) goto error;

        return 0;

error:
        LOG_ERROR(ret, "error setting up tracer as active snapshot");
        tracer_destroy(dev);
        return ret;
}
```
**Tracing process**
```
static int wait_cow_completion(struct snap_device *dev,  unsigned int minor){
        int ret;

        wake_up_process(dev->sd_cow_thread);

        //inject the tracing function
        ret = __tracer_setup_tracing(dev, minor);
        if(ret) goto error;

        return 0;

error:
        LOG_ERROR(ret, "error setting up tracer as active snapshot");
        tracer_destroy(dev);
        return ret;
}

```

Can I pull request for this issue?

Best Regards,
Nick

**Comment by dakotarwilliams** [comment]
> is it possible that the disk in target machine has some data consistency issues?
Absolutely, dattobd isn't concerned with application consistency, considering it's scope is limited to just block device consistency. In our product we get around this by providing a place to put scripts that interface with applications that need consistency across disks. This is not to say that this is a bad solution, this certainly helps. We even have a notion of snapshot sets for our Windows analogue, so your change brings dattobd in line with that style. It's to say that this mitigates a lot of application inconsistency, since the time for inconsistency to happen on multi-core systems is minimized.

So short answer: sure, put up an PR for it. Internally dattobd hasn't really been a priority, so getting the validation and actually merging a complete and functional PR might take a long time.

**Comment by nickchen-cpu** [comment]
Hi, @dakotarwilliams
Thanks for replying!
I will keep going and try to pull request to solve the ```inconsistency``` and the ```dynamic allocation```
Your advices is very helpful to me!

Best Regards,
Nick

**Comment by nixomose** [comment]
"For instance, if sda1 and sda2 take only some seconds to allocate COW files but sda3 take several minutes to create the one, is it possible that the disk in target machine has some data consistency issues?"

So... if you mentioned what filesystem you're talking about, I missed it, but where possible, dattobd uses fallocate, which is pretty quick as it writes almost no data on most modern filesystems
.
taking 90 seconds to do an fallocate doesn't sound right.

we've seen things like this on ntfs (I forget which ntfs implementation exactly) but  it's an odd use case that requires application consistency across multiple disks on linux on ntfs...

**Comment by nickchen-cpu** [comment]
Hi, @nixomose ,
Thank you for your reply!

Some of users want to keep their kernel versions or filesystems old, such as 2.6.23 or lower kernel versions or ext3, where we will use ```file_write``` to write ```0``` to create COW files; 

In my case, it takes almost 1 hour to ```file_write``` COW for apache server(whose specification is **1TB / ext3 / HDD/IDE port**).

I was so pleased to hear from you!
Best Regards,
Nick
