### ISSUE TITLE
debian 11 bullseye and kernel 5.10 support?

### ISSUE THREAD

**Issue by xretia** [datto/dattobd#259]
need support for debian 11 bullseye and kernel 5.10?

**Comment by nixomose** [comment]
see this, it may help you...
https://github.com/datto/dattobd/issues/252#issuecomment-917749988

**Comment by dfc643** [comment]
@nixomose thank you so much! it works like a charm

**Comment by Swistusmen** [comment]
Support for debian 11 and kernel 5.10 has been provided
