### ISSUE TITLE
snapshot for /dev/sda1 hung on CentOS 8.4

### ISSUE THREAD

**Issue by zhanghaiyang9999** [datto/dattobd#260]
OS: CentOS Linux release 8.4.2105
Kernel Version: 4.18.0-305.19.1.el8_4.x86_64/4.18.0-305.7.1.el8_4.x86_64

run command:
dbdctl setup-snapshot /dev/sda1 /boot/.datto 0

After a while, will lead the OS hung, the /dev/sda1 is /boot volume, xfs filesystem.

and some errors in dmesg

[  172.512467] datto: error finding original_mrf: -14
[  174.128111] datto: error finding original_mrf: -14
[  181.728482] datto: error finding original_mrf: -14
[  181.728552] datto: error finding original_mrf: -14
[  181.728691] datto: error finding original_mrf: -14
[  181.728904] datto: error finding original_mrf: -14

**Comment by yito24** [comment]
It has been fixed in the forked elastio driver.
But it hasn't been fixed in dattobd yet. 

#252

**Comment by dakotarwilliams** [comment]
Fixed #264
