### ISSUE TITLE
Unable to build for kernel 5.4 on Centos 7

### ISSUE THREAD

**Issue by EvgeniySpinov** [datto/dattobd#267]
First of all thank you for the great tool. I'm using dattobd on multiple systems where it works without issues.

However currently I have not typical setup:
- I have elrepo kernel for Centos 7 (kernel-lt-5.4.172-1.el7.elrepo.x86_64) 
- I'm trying to install dattobd. 

Build fails with a huge error log with errors all over the place ([make.log](https://github.com/datto/dattobd/files/7889385/make.log)). Googling on few of them leads me to a dead end.

To my understanding kernel 5.4 is supported and module should be compiled without issues. Am I right?

**Comment by nickchen-cpu** [comment]
Hi
All of your pre-compile is **not present**
I guess it's because GPL
Please try following method:
insert this line in include.h
![image](https://user-images.githubusercontent.com/70849044/149970484-c62ef80a-d0c9-48d0-a5aa-ba697c7a9eb9.png)

```
make clean
make
```

to see if it's ok .

**Comment by EvgeniySpinov** [comment]
Thank you for prompt response. 

Did exactly what is on the image in the file is called "src/includes.h".

It doesn't seemed to have changed anything - I still get the same amount and type of errors.

**Comment by nickchen-cpu** [comment]
Did you ever update your kernel-devel-$(uname -r).rpm?
After update kernel, you also need to update the kernel-devel-rpm which is the API headers lib so that datto can understand your kernel.

https://centos.pkgs.org/7/elrepo-kernel-x86_64/kernel-lt-devel-5.4.172-1.el7.elrepo.x86_64.rpm.html
Please try to install it

**Comment by EvgeniySpinov** [comment]
Sure, I have these packages in the system initially (otherwise it refuses to even start compilation):
kernel-lt-devel-5.4.172-1.el7.elrepo.x86_64
kernel-lt-5.4.172-1.el7.elrepo.x86_64
kernel-lt-headers-5.4.172-1.el7.elrepo.x86_64

As well as I'm currently booted in the same kernel:
Linux hostname 5.4.172-1.el7.elrepo.x86_64 #1 SMP Fri Jan 14 13:01:57 EST 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nickchen-cpu** [comment]
https://github.com/aabc/ipt-netflow/issues/171
Found a persion which also use CentOS 7 kernel 5.4
And symptom like being related to asm __inline support
Can you try this method?

**Comment by EvgeniySpinov** [comment]
Thank you for help! That solution works for me.
