### ISSUE TITLE
Fails to locate 2 packages on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by General-Zimmer** [datto/dattobd#278]
Hey, I tried to install dattobd with on a Ubuntu 22.04 LTS VM

```
sudo apt-key adv --fetch-keys https://cpkg.datto.com/DATTO-PKGS-GPG-KEY
echo "deb [arch=amd64] https://cpkg.datto.com/datto-deb/public/$(lsb_release -sc) $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/datto-linux-agent.list
sudo apt-get update
sudo apt-get install dattobd-dkms dattobd-utils
```

but it seems like 2 packages aren't located

```
root@wisecraft:~# sudo apt-get install dattobd-dkms dattobd-utils                                                                                                                                                                            Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package dattobd-dkms
E: Unable to locate package dattobd-utils
```

**Comment by masterwishx** [comment]
Having same isshue but only - Unable to locate package dattobd-utils

using Ubuntu 20.04.4 LTS (GNU/Linux 5.13.0-1036-oracle aarch64)

**Comment by dakotarwilliams** [comment]
Still working our way toward kernel 5.15 compat - no packages yet, it won't build.

**Comment by masterwishx** [comment]
> Still working our way toward kernel 5.15 compat - no packages yet, it won't build.

Thanks for answer , it will work on Linux 5.13.0-1036-oracle aarch64 ? 
When will be ready ( i mean on aarch64) and oracle cloud ?

also tryed https://github.com/elastio/elastio-snap
that froked from here and its working but i need dattobd for urbackup and autobackup

**Comment by rmaxwell72** [comment]
Is there any update on this yet?  Still currently not working on Ubuntu 22.04 or any linux with a 5.15+ kernel from my experience.

Thanks,

**Comment by General-Zimmer** [comment]
> 

Nope, no update yet. I'm still performing manual backups at the moment.

**Comment by scoobaspeaz** [comment]
im starting to think this project is abandoned. Odd that no updates to this post from any devs since July

**Comment by adnanshaheen** [comment]
> im starting to think this project is abandoned. Odd that no updates to this post from any devs since July

We are working on supporting latest distros. Stay tuned.

**Comment by rmaxwell72** [comment]
> > im starting to think this project is abandoned. Odd that no updates to this post from any devs since July
> 
> We are working on supporting latest distros. Stay tuned.

Maybe posting a timeline would be helpful, as this still feels that the overall project is abandoned.  I can't believe that for what Datto charges, that they are telling clients that they cannot backup 5.15+ kernels, whether debian or RHEL based distros.

**Comment by adnanshaheen** [comment]
Please check https://github.com/datto/dattobd/releases/tag/v0.11.0

**Comment by Kazz3r24** [comment]
When I run 'make' and 'make install' everything appears to go fine but when trying 'modprobe dattobd' I get 
"modprobe: FATAL: Module dattobd not found in directory /lib/modules/5.15.0-58-generic"

Do I need to restart my server before I'll be able to install dattobd?

**Comment by nixomose** [comment]
Have you rebooted since your last kernel upgrade? You might be running a
different kernel than you would boot to.

**Comment by Kazz3r24** [comment]
Yes, it just rebooted this morning and I can confirm getting the same error only it's 5.15.0-60-generic now.

**Comment by JM-AIV** [comment]
Any update on this? Rumor has it Datto would add 22.04 LTS support at Q1 2023, but is there anyone who can confirm this?

**Comment by madgamer98** [comment]
> Yes, it just rebooted this morning and I can confirm getting the same error only it's 5.15.0-60-generic now. I re-ran make and make install after the reboot.

I had the same issue/error. I fixed it by running "depmod" after the make and make install and after that "modprobe dattobd" was able to find the module. Rebooting by itself didn't work.

**Comment by Kazz3r24** [comment]
Can confirm that running depmod then 'modprobe dattobd' worked for me as well. Thank you very much for this!

**Comment by alphandbelt** [comment]
> Can confirm that running depmod then 'modprobe dattobd' worked for me as well. Thank you very much for this!

I also meet this on 5.15.0-89-generic ubuntu20.04.1 . and run depmod and then solve this problem, but why?

**Comment by Swistusmen** [comment]
We'll investigate this issue with depmod

**Comment by Swistusmen** [comment]
Hello everybody, I inform you that we release our product with support of ubuntu 22 (kernel 5.15) and rhel 9.3

**Comment by dinghuaming** [comment]
@Swistusmen  hi, does dattodb support kernel 5.15.67?
 if it support kernel 5.15.67, which branch support?
thanks!

**Comment by Swistusmen** [comment]
@dinghuaming I have responded you here: https://github.com/datto/dattobd/issues/359
