### ISSUE TITLE
is it working on Oracle Cloud ?

### ISSUE THREAD

**Issue by masterwishx** [datto/dattobd#281]
tryed install on oracle cloud but having - Unable to locate package dattobd-utils 
using Ubuntu 20.04.4 LTS (GNU/Linux 5.13.0-1036-oracle aarch64)

is is should work in Oracle Cloud ,they having some oracle snapshot system ?

**Comment by dakotarwilliams** [comment]
> aarch64

See #248 

At the moment, ARM support is not on our roadmap.

**Comment by masterwishx** [comment]
> At the moment, ARM support is not on our roadmap.

sorry , i see

**Comment by masterwishx** [comment]
still not supported ARM?

**Comment by Swistusmen** [comment]
Unfortunately we still don't support ARM

**Comment by masterwishx** [comment]
Thanks got it

**Comment by masterwishx** [comment]
any news for arm ?

**Comment by Swistusmen** [comment]
nope, you can check our tags to see what we are currently releasing
