### ISSUE TITLE
Kernel panic in cow_read_mapping

### ISSUE THREAD

**Issue by lishuai-ujs** [datto/dattobd#286]
centos 7.6.1810
3.10.0-957.el7.x86_64

![图片](https://user-images.githubusercontent.com/19320338/191700632-71c38f6f-52b1-4838-a77f-754ea61d429d.png)

![图片](https://user-images.githubusercontent.com/19320338/191700780-e721d9c0-53d2-45e7-a667-794b39d3547f.png)

![图片](https://user-images.githubusercontent.com/19320338/191701573-c9e0bfd2-e666-451a-8a5c-a7d75b521806.png)

copy snapshot of /dev/vdc，kernel panic

![图片](https://user-images.githubusercontent.com/19320338/191701282-aba1e120-2cfb-4df4-b526-64fdb179d1cf.png)

![图片](https://user-images.githubusercontent.com/19320338/191747006-181ebbae-84f8-4000-98fc-94582d410e58.png)

![图片](https://user-images.githubusercontent.com/19320338/191747307-b4e426c4-5244-4154-933f-bcd96c44def5.png)

**Comment by nickchen-cpu** [comment]
please try ```xfs_repair``` it and then try again.

**Comment by lishuai-ujs** [comment]
I add flow print code in cow_read_mapping and find the pos is out of bound of array when kernel panic.
![图片](https://user-images.githubusercontent.com/19320338/192199158-bf61a9d8-0b99-49c4-8325-4b48cbbdade3.png)
![图片](https://user-images.githubusercontent.com/19320338/192199204-1bbdeab4-09d7-4fb3-981a-cf0d3bae6e2f.png)

**Comment by lishuai-ujs** [comment]
> I tried, but it not works. It's maybe a bug of dattobd.

**Comment by lishuai-ujs** [comment]
accord to the vmcore, cow_read_mapping is called from snap_read_bio_get_mode
![图片](https://user-images.githubusercontent.com/19320338/192199916-459e95ac-77fe-4452-9616-f312274f376b.png)
![图片](https://user-images.githubusercontent.com/19320338/192199965-5e17cf4b-0881-43e7-9538-0e91ee374367.png)

I add flow trace code and find the **curr_end_bytes is uncorrect in second cycle of while loop, curr_end_bytes shound minus the bytes have read in first cycle.**
![图片](https://user-images.githubusercontent.com/19320338/192200105-4a4b81ac-9726-4a84-b83e-edc48f424268.png)
![图片](https://user-images.githubusercontent.com/19320338/192200782-365d9c55-d7f3-4bf9-a376-92c46ad7b8cf.png)

**Comment by dakotarwilliams** [comment]
Resolved #287

**Comment by jcbmao** [comment]
> centos 7.6.1810 3.10.0-957.el7.x86_64
> 
> ![图片](https://user-images.githubusercontent.com/19320338/191700632-71c38f6f-52b1-4838-a77f-754ea61d429d.png)
> 
> ![图片](https://user-images.githubusercontent.com/19320338/191700780-e721d9c0-53d2-45e7-a667-794b39d3547f.png)
> 
> ![图片](https://user-images.githubusercontent.com/19320338/191701573-c9e0bfd2-e666-451a-8a5c-a7d75b521806.png)
> 
> copy snapshot of /dev/vdc，kernel panic
> 
> ![图片](https://user-images.githubusercontent.com/19320338/191701282-aba1e120-2cfb-4df4-b526-64fdb179d1cf.png)
> 
> ![图片](https://user-images.githubusercontent.com/19320338/191747006-181ebbae-84f8-4000-98fc-94582d410e58.png)
> 
> ![图片](https://user-images.githubusercontent.com/19320338/191747307-b4e426c4-5244-4154-933f-bcd96c44def5.png)

“What are the conditions for reproducing this crash?”

“I created a 5TB disk, formatted it with XFS file system, then took a snapshot. When I use the ‘dd’ command to read the snapshot, the machine doesn’t crash.”
