### ISSUE TITLE
RHEL 9 / Oracle Linux 9 Support

### ISSUE THREAD

**Issue by scoobaspeaz** [datto/dattobd#293]
I cannot seem to find support for RHEL/OL 9. Am I looking in the wrong place for the package or is it not supported yet? If not, do you know if/when it will be supported?

**Comment by Swistusmen** [comment]
Hi, supporting RHEL 9 is our top priority. For now dattobd succesfully build on RHELs 9.0-9.2 but on 9.1-9.2 hang while performing dbdctl setup-snapshot.

**Comment by yito24** [comment]
I tested 0.11.6 on RHEL 9.1 / 9.3.
It was able to successfully execute snapshots.

**Comment by Swistusmen** [comment]
That's great to hear, we also confirm that it works on this OSes, althoguh I have a question for you @yito24 , on which filesystem have you tested xfs or ext4? Have you tried to restore a backup? How did it go?
