### ISSUE TITLE
Debian repository for bookworm (12) missing

### ISSUE THREAD

**Issue by daniel-blake** [datto/dattobd#318]
When installing dattobd on multiple systems, I noticed that the debian repository for bookworm (debian 12) does not yet exist.
It would be nice if that could be added. While I can compile my own deb packages, having the "official" ones would be more prefereable.

**Comment by Swistusmen** [comment]
Hello @daniel-blake we are working on this, it's my top priority for now

**Comment by schwitters** [comment]
```bash
bookworm :
sudo apt-get install linux-headers-$(uname -r) build-essential git devscripts lintian dkms pax
wget "https://github.com/debbuild/debbuild/releases/download/22.02.1/debbuild_22.02.1-0ubuntu20.04_all.deb"
dpkg -i debbuild_22.02.1-0ubuntu20.04_all.deb && rm -f debbuild_22.02.1-0ubuntu20.04_all.deb
git clone https://github.com/datto/dattobd.git
cd dattobd/
git checkout  v0.11.3
make deb
sudo dpkg -i pkgbuild/DEBS/all/dattobd-dkms_0.11.3-1debian12_all.deb
sudo dpkg -i pkgbuild/DEBS/amd64/libdattobd1_0.11.3-1debian12_amd64.deb
sudo dpkg -i pkgbuild/DEBS/amd64/dattobd-utils_0.11.3-1debian12_amd64.deb

```

**Comment by absolution1** [comment]
Thanks
Will this build on ARM (RPi4B)?

**Comment by schwitters** [comment]
> Thanks Will this build on ARM (RPi4B)?

Untested. 
uname -a
Linux sv-testdb-2022 6.1.0-13-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux

**Comment by nixomose** [comment]
A long time ago like 2016 or so I got dattobd to run on a raspi but that was 32 bit and a long long time ago.
So at least it was possible.

**Comment by bg** [comment]
I guess with https://github.com/datto/dattobd/issues/349 now closed, it's only a matter of time now before we can finally see a release for Debian 12 (bookworm) which includes the linux 6.1 kernel?

**Comment by Swistusmen** [comment]
I confirm it builds on 6.1, although doesn't work. We have just created a tag 0.11.7 with support for rhel 9, and now picking up another stuff. Please follow https://continuity.datto.com/help/Content/kb/siris-alto-nas/360040893811.html

**Comment by synrg** [comment]
Ah, that's too bad. Thanks for the info - saves me the bother of trying it myself. You say "follow" - is there a way to actually do that? RSS feed, or ... ? If it's a matter of periodically checking that page, I very likely will forget to do so.

**Comment by Swistusmen** [comment]
I don't know :/ I am not working on sales nor marketing. I think you can observe this repo, and everytime tag will be made look forward to get info about debian 12/ ask about it than

**Comment by bg** [comment]
Fair. I'm already monitoring releases by subscribing to it in github, so that'll do. Thanks.
