### ISSUE TITLE
kernel 6+

### ISSUE THREAD

**Issue by sunilkalra123** [datto/dattobd#349]
Hi, is there any news on if/when dattodb will support kernel 6+?

**Comment by Swistusmen** [comment]
Hi, which precisely? I

**Comment by sunilkalra123** [comment]
Hi Michel, i was hoping for 6.2 as thats what Ubuntu 22.04 HWE uses and Debian 12 is on 6.1

**Comment by Swistusmen** [comment]
I have build it on 6.1 but didn't test- you may try do to it. Support for these kernels is of our goals, but I cannot provide you any official informations.
