### ISSUE TITLE
Repository links broken

### ISSUE THREAD

**Issue by uroni** [datto/dattobd#35]
E.g.

https://cpkg.datto.com/datto-rpm/EnterpriseLinux/6/x86_64/datto-el-rpm-release-6-8.1.noarch.rpm

does not work.

**Comment by Conan-Kudo** [comment]
Hello @uroni,

Thank you for trying out dattobd. We recently rejiggered the repository configuration package as we added more distributions to support (again!), which unfortunately led to the old URLs breaking.

I've already submitted #36 to fix this.

**Comment by Conan-Kudo** [comment]
@uroni From this point on, the repository configuration package URLs should be fairly static, as the URLs are now outside of the repositories themselves.

**Comment by Conan-Kudo** [comment]
@uroni Once #38 is merged, you'll have a reliable path that should always work in the documentation.

**Comment by tcaputi** [comment]
merged

**Comment by uroni** [comment]
Thanks!
