### ISSUE TITLE
Plans for aarch64 support

### ISSUE THREAD

**Issue by evant89** [datto/dattobd#353]
Hi team!
We appreciate your work and thank you!

Tell me, do you have any plans for aarch64?
For an example of using the Ampere instances on Oracle 
Cloud.

**Comment by Swistusmen** [comment]
Hi, all I can say it is something what would be nice to have. I am not allowed to say more. If you are a Kaseya client than asking about it product support may speed up the process of providing support for it.
Thanks for kind words and wish you a good day
