### ISSUE TITLE
Centos 8 - Dont' install

### ISSUE THREAD

**Issue by paweldesign** [datto/dattobd#358]
```
root@serverweb:# htop
root@serverweb:# sudo yum localinstall https://cpkg.datto.com/datto-rpm/repoconfig/datto-el-rpm-release-$(rpm -E %rhel)-latest.noarch.rp
ookla_speedtest-cli                                                                                                                                                                                          295  B/s | 833  B     00:02
ookla_speedtest-cli-source                                                                                                                                                                                   303  B/s | 833  B     00:02
[MIRROR] datto-el-rpm-release-8-latest.noarch.rp: Status code: 404 for https://cpkg.datto.com/datto-rpm/repoconfig/datto-el-rpm-release-8-latest.noarch.rp (IP: 8.34.181.206)
[MIRROR] datto-el-rpm-release-8-latest.noarch.rp: Status code: 404 for https://cpkg.datto.com/datto-rpm/repoconfig/datto-el-rpm-release-8-latest.noarch.rp (IP: 8.34.181.206)
[MIRROR] datto-el-rpm-release-8-latest.noarch.rp: Status code: 404 for https://cpkg.datto.com/datto-rpm/repoconfig/datto-el-rpm-release-8-latest.noarch.rp (IP: 8.34.181.206)
[MIRROR] datto-el-rpm-release-8-latest.noarch.rp: Status code: 404 for https://cpkg.datto.com/datto-rpm/repoconfig/datto-el-rpm-release-8-latest.noarch.rp (IP: 8.34.181.206)
[FAILED] datto-el-rpm-release-8-latest.noarch.rp: Status code: 404 for https://cpkg.datto.com/datto-rpm/repoconfig/datto-el-rpm-release-8-latest.noarch.rp (IP: 8.34.181.206)
Status code: 404 for https://cpkg.datto.com/datto-rpm/repoconfig/datto-el-rpm-release-8-latest.noarch.rp (IP: 8.34.181.206)
root@serverweb:# sudo yum install dkms-dattobd dattobd-utils
Ultima verifica della scadenza dei metadati: 0:00:27 fa il mer 28 feb 2024 14:50:27 CET.
Nessuna corrispondenza per l'argomento: dkms-dattobd
Nessuna corrispondenza per l'argomento: dattobd-utils
Errore: Impossibile trovare una corrispondenza: dkms-dattobd dattobd-utils
root@serverweb:# ^C
root@serverweb:# curl -O https://cpkg.datto.com/datto-rpm/EnterpriseLinux/7/x86_64/datto-el-rpm-release-1.0.0-1.noarch.rpm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    375      0 --:--:-- --:--:-- --:--:--   375
root@serverweb:# sudo yum localinstall datto-el-rpm-release-1.0.0-1.noarch.rpm
ookla_speedtest-cli                                                                                                                                                                                          293  B/s | 833  B     00:02
ookla_speedtest-cli-source                                                                                                                                                                                   400  B/s | 833  B     00:02
Can not load RPM file: datto-el-rpm-release-1.0.0-1.noarch.rpm.
Impossibile aprire: datto-el-rpm-release-1.0.0-1.noarch.rpm
root@serverweb:#
```

how to fix? Thank you

**Comment by Swistusmen** [comment]
Hi, for Centoses 8.0-8.3 are not supported. Which one do you use? Also we are not longer focusing on supporting Centoses, so if normal installation doesn't work for you, I would recommend building it on your own

**Comment by paweldesign** [comment]
ok..Thank You

**Comment by st-matskevich** [comment]
Although CentOS 8 below 8.9 is not officially fully supported, it looks like in your case you just mistyped URL and forgot `m` at the end.

Try running `sudo yum localinstall https://cpkg.datto.com/datto-rpm/repoconfig/datto-el-rpm-release-$(rpm -E %rhel)-latest.noarch.rpm`
Instead of `sudo yum localinstall https://cpkg.datto.com/datto-rpm/repoconfig/datto-el-rpm-release-$(rpm -E %rhel)-latest.noarch.rp`

**Comment by paweldesign** [comment]
`sudo yum localinstall https://cpkg.datto.com/datto-r                                                                                                                                                             pm/repoconfig/datto-el-rpm-release-$(rpm -E %rhel)-latest.noarch.rpm
ookla_speedtest-cli                             349  B/s | 833  B     00:02
ookla_speedtest-cli-source                      347  B/s | 833  B     00:02
datto-el-rpm-release-8-latest.noarch.rpm         26 kB/s |  12 kB     00:00
Dipendenze risolte.
================================================================================
 Package                    Architecture Version       Repository          Size
================================================================================
Installing:
 datto-el-rpm-release       noarch       8-12.1        @commandline        12 k

Riepilogo della transazione
================================================================================
Installati  1 pacchetto

Dimensione totale: 12 k
Dimensione installata: 4.2 k
Procedere [s/N]: s
Scaricamento dei pacchetti:
Esecuzione del controllo di transazione
Controllo di transazione eseguito con successo.
Test di transazione in corso
Test di transazione eseguito con successo
Transazione in corso
  Preparazione in corso        :                                            1/1
  Installing                   : datto-el-rpm-release-8-12.1.noarch         1/1
  Verifica in corso            : datto-el-rpm-release-8-12.1.noarch         1/1

Installati:
  datto-el-rpm-release-8-12.1.noarch

Fatto!
`

thank you....thank you

**Comment by st-matskevich** [comment]
Don't forget to proceed with remaining installation steps, you still need to run this to complete dattobd installation:  
`sudo yum install dkms-dattobd dattobd-utils`  
Closing the issue as resolved.

**Comment by paweldesign** [comment]
Thank you for your support
Solved!
