### ISSUE TITLE
Can't get this to install on Ubuntu 22.04

### ISSUE THREAD

**Issue by tony95i** [datto/dattobd#370]
I have tried 22.04.4 and 22.04.2. Is this supported with Desktop? I am also running it in Hyper-V.
[term1.log](https://github.com/datto/dattobd/files/14923854/term1.log)
I attached the log.
`Errors were encountered while processing:
 dattobd-dkms
 dattobd-utils
 dlad`

I have tried sudo depmod and sudo modprobe dattobd but it says module not found. I really don't know what to do and I need to get this working.

**Comment by Swistusmen** [comment]
Hi, I see that the kernel you are using is 6.5, our current version unfortunately does not support this kernel, but keep calm as updates are coming

**Comment by tony95i** [comment]
> Hi, I see that the kernel you are using is 6.5, our current version unfortunately does not support this kernel, but keep calm as updates are coming

Thank you for the quick response. So the Datto Web site says 22.04 is supported
https://continuity.datto.com/help/Content/kb/siris-alto-nas/360040893811.html
I will try to install the very first version of 22.04 and see if that works. Otherwise, I am going to have to find another backup strategy because I need to create nightly images of an email server without shutting down.

**Comment by Swistusmen** [comment]
Yes, but we are supporting 5.15 for now (it's for ubuntu 22 LTS). We are working on providing support for new kernels, so I would keep an eye on updates on your place

**Comment by joriverm** [comment]
@Swistusmen : any updates on this? my employer is looking into datto to support all devices it needs to (macs, windows and linux) but i am using a framework laptop, which is only (decently) supported in more recent linux kernels.

im also using linux mint, and noticed the script not finding the packages, but i fixed that locally as that is totally on me, and im ok with that bit :)

**Comment by Swistusmen** [comment]
@joriverm I am no longer working for this company, I cannot provide you with any information

**Comment by joriverm** [comment]
whoops, sorry to have pinged you then!

**Comment by Swistusmen** [comment]
no prob,wish you good luck
