### ISSUE TITLE
Very Slow to take snapshot

### ISSUE THREAD

**Issue by yito24** [datto/dattobd#373]
It is slow to take snapshots of 0.11.7.
For 0.11.6, it takes about **0.342 seconds** to snapshot 4 volumes.
For 0.11.7, it takes about **27 seconds** to snapshot 4 volumes.

Why does it take so long?

[0.11.6.txt](https://github.com/datto/dattobd/files/15270447/0.11.6.txt)
[0.11.7.txt](https://github.com/datto/dattobd/files/15270448/0.11.7.txt)
[lsblk.txt](https://github.com/datto/dattobd/files/15270449/lsblk.txt)

**Comment by Swistusmen** [comment]
Hi, thank you for noticing that, we will make investigations about this topic in the future, but for now, it seems to be good enough. Slow down is caused by switching block-layer API in kernel 5.9

**Comment by yito24** [comment]
Thanks for your reply.

I tried it on CentOS7.9, but it takes about 27 seconds.
If the timing of snapshots of each volume is shifted, there is a concern that it will affect Oracle etc.

[backup_20240517102348.txt](https://github.com/datto/dattobd/files/15342642/backup_20240517102348.txt)

**Comment by Swistusmen** [comment]
We are trying to firstly satisfy our primary limited distributions which are listed here: https://continuity.datto.com/help/Content/kb/siris-alto-nas/360040893811.html for now we have other concerns to focus on. If the speed will become a real obstacle for us, we will focus on that much more
