### ISSUE TITLE
Hangs when running dbdctl destroy

### ISSUE THREAD

**Issue by yito24** [datto/dattobd#374]
If it have a partition layout where /home is separate, attempting to destroy a snapshot of /home will hang.

Does not occur on RHEL9.3.
This is occurring on RHEL8.9.

NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda      8:0    0  100G  0 disk 
├─sda1   8:1    0  600M  0 part /boot/efi
├─sda2   8:2    0    1G  0 part /boot
├─sda3   8:3    0   50G  0 part /
├─sda4   8:4    0    4G  0 part [SWAP]
└─sda5   8:5    0 44.5G  0 part /home　
sr0     11:0    1 1024M  0 rom  
datto0 253:0    0  600M  1 disk 
datto1 253:1    0    1G  1 disk 
datto2 253:2    0   50G  1 disk 
datto3 253:3    0 44.5G  1 disk    -------->When I run "dbdctl destroy 3",  hang here.

I tried below driver.
**0.11.8   Not hang   ------> New status**
0.11.7   hang
0.11.6   hang
0.11.5   hang
0.11.4   hang
0.11.3   hang
0.11.0   hang
0.10.16 Not hang

**Comment by hongyuntw** [comment]
can you provide the dmesg when you destroy the snap device?

**Comment by lianghairun93** [comment]
When both a vfat partition and other partitions exist, destroy the snapshot may cause a hang。
The following scenarios were tested：
I tested the following scenarios on CentOS 7.9：
1.sdb
├─sdb1          vfat              BB2E-8006
└─sdb2          xfs               eef96e9a-290c-4841-8652-6ae80e7a4f3a
hang

2.sdb
├─sdb1          vfat              BB2E-8006
not hang

3.sdb
└─sdb1          xfs               eef96e9a-290c-4841-8652-6ae80e7a4f3a
not hang

**Comment by lianghairun93** [comment]
When both a vfat partition and other partitions exist, destroy the snapshot may cause a hang。
The following scenarios were tested：
I tested the following scenarios on CentOS 7.9：
1.sdb
├─sdb1          vfat              BB2E-8006
└─sdb2          xfs               eef96e9a-290c-4841-8652-6ae80e7a4f3a
hang

2.sdb
├─sdb1          vfat              BB2E-8006
not hang

3.sdb
└─sdb1          xfs               eef96e9a-290c-4841-8652-6ae80e7a4f3a
not hang

**Comment by yito24** [comment]
Hi lianghairun93,

I tested with the 0.11.8 driver.
I confirmed that this issue is resolved in RHEL7.x and RHEL8.x

Does this happen in your environment with the 0.11.8 driver?
