### ISSUE TITLE
After executing destroy command, the .datto file is not deleted and occurs "error unlinking file: -1"

### ISSUE THREAD

**Issue by yito24** [datto/dattobd#386]
I am testing in RHEL OS.
driver version: 0.11.8

After taking a snapshot, ran the destroy command to check the behavior of the .datto file.
- The .datto file is not deleted.
- The following message occurs.
 kernel: datto: error unlinking file: -1

Please check the attachment log.
[el7.txt](https://github.com/user-attachments/files/16989123/el7.txt)
[el8.txt](https://github.com/user-attachments/files/16989124/el8.txt)
[el9.txt](https://github.com/user-attachments/files/16989127/el9.txt)

Similar issue
https://github.com/datto/dattobd/issues/369

**Comment by iamandrii** [comment]
Hi @yito24; Thanks for your message. We know about this issue, and we currently are in process of fixing that.

But don't worry, this issues does not affect taking snapshots and tracking changes in any bad way, they are just more "cosmetic" ones.

**Comment by yito24** [comment]
This issue has been fixed in 0.11.9.
