### ISSUE TITLE
Mount issue for Redhat 8.10 in the latest dattobd update (0.11.8)

### ISSUE THREAD

**Issue by santhocoren** [datto/dattobd#387]
mount issue for Redhat 8.10 in the latest dattobd update (0.11.8)

my server gets restarted when execute the mount command in the latest dattobd update(0.11.8), please check and resolve asap. thanks

**execute the command:**

dbdctl setup-snapshot /dev/sdb1 /data1/.datto 0

**mount -o ro,noload /dev/datto0 /test1 ()**  - when server hangs and restarts

**Comment by iamandrii** [comment]
Hi @sancorent. Thanks for your concerns, we are already in process of fixing the issue. I've replied to you in separate issue about steps to apply fix before it'd be publicly available.

Sorry for any inconveniences. Do not hesitate to contact in case you need further assistance.

**Comment by sancorent** [comment]
@iamandrii Thanks for your quick response. There is when to expect the next update the release for fix?

**Comment by iamandrii** [comment]
Hi, released just now!
