### ISSUE TITLE
Creating COW file takes a long time

### ISSUE THREAD

**Issue by yito24** [datto/dattobd#392]
I found the cause why it take a long time to take a snapshot.
**Related issues**
https://github.com/datto/dattobd/issues/383

Ver 0.11.7 and later, it takes a long time to create a COW file that is 10% of the volume.
**There is a problem with the behavior of creating COW files.**
**Please fix this issue so that COW files can be created immediately.**

I tested it with a 5TB volume.
<pre>
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda      8:0    0    5T  0 disk 
├─sda1   8:1    0  200M  0 part /boot/efi
├─sda2   8:2    0    1G  0 part /boot
├─sda3   8:3    0  3.9G  0 part [SWAP]
├─sda4   8:4    0   50G  0 part /
└─sda5   8:5    0    5T  0 part /home
</pre>

Ver 0.11.6, it takes less than 0.1 seconds to create a 500GB COW file, for example.
[Ver0.11.6.txt](https://github.com/user-attachments/files/17303470/Ver0.11.6.txt)
<pre>
10/09/2024 06:35:33.630 ** datto file does not exist.
10/09/2024 06:35:34.098 ** dbdctl setup-snapshot /dev/sda5 /home/.datto0 0
10/09/2024 06:35:34.105 507G .datto0 　------------->10% COW file is created immediately
10/09/2024 06:35:34.117 ** Created snapshot /dev/sda5.
10/09/2024 06:35:34.121 ** sleep 5.
10/09/2024 06:35:39.129 ** dbdctl destroy 0.
10/09/2024 06:35:39.154 ** destroy fin.
</pre>
Ver 0.11.7 and later, it takes 30 minutes to create a 500GB COW file.
[Ver0.11.8.txt](https://github.com/user-attachments/files/17303472/Ver0.11.8.txt)
<pre>
10/09/2024 05:44:24.022 ** datto file does not exist.
10/09/2024 05:44:24.902 ** dbdctl setup-snapshot /dev/sda5 /home/.datto0 0
10/09/2024 05:44:25.034 ** datto file does not exist.
10/09/2024 05:44:26.040 342M .datto0
10/09/2024 05:44:27.051 921M .datto0
            :
            :
10/09/2024 06:15:08.194 506G .datto0
10/09/2024 06:15:10.888 507G .datto0 　------------->It takes 30 minutes to create 10% of the COW file
10/09/2024 06:15:13.268 ** Created snapshot /dev/sda5.
10/09/2024 06:15:13.926 ** sleep 5.
10/09/2024 06:15:18.931 ** dbdctl destroy 0.
10/09/2024 06:15:20.648 ** destroy fin.
</pre>

**Comment by iamandrii** [comment]
Hi @yito24. Thanks for raising this again. I think I know the reason (starting from `0.11.7` we are using our `fallocate` instead of kernel one). We will proceed with this bug in one of our next releases. Have a nice day =)

**Comment by yito24** [comment]
Hi @iamandrii,

I was download "dattobd-real-fallocate-fix" and tested it, but the basic partition is a little slow.
[backup_20241023104106.txt](https://github.com/user-attachments/files/17484014/backup_20241023104106.txt)
[lsblk.txt](https://github.com/user-attachments/files/17484015/lsblk.txt)

Is it possible to create COW faster?
In the case of Ver0.11.6, the COW creation speed is within 0.3 seconds.

**Comment by yito24** [comment]
Hi @iamandrii,

I was download "dattobd-real-fallocate-fix" and tested it.
I have confirmed that the COW is created in a similar amount of time as in version 0.11.6.

**Comment by yito24** [comment]
This issue has been fixed in 0.11.9.
