### ISSUE TITLE
Dattobd kernel module error

### ISSUE THREAD

**Issue by jrosetto** [datto/dattobd#43]
I've tried Ubuntu 16.04.1 LTS as well as 14.04 LTS running under VMWare ESXi and I keep getting kernel errors.  I installed using the REPO in the install documentation.  Here is the exact error.

dattobd: module verification failed: signature and/or required key missing - tainting kernel

Any suggestions on how to get around this issue?

**Comment by tcaputi** [comment]
This actually isnt really an error. A kernel taint just means that you have some unverified code running in your kernel. Its a security measure to prevent your system from installing a desired kernel module, only to have someone switch it out and run unwanted code in the kernel. 

If you run `lsmod | grep dattobd` you should see that it is loaded. If you care about the warning, I encourage you to look into [kernel module signing](https://www.kernel.org/doc/Documentation/module-signing.txt)

**Comment by jrosetto** [comment]
I assume you are talking about lsmod here is my output.

dattobd                49152  0

**Comment by tcaputi** [comment]
Yes. That is what you should see. The module is loaded and running.
