### ISSUE TITLE
CentOS 5: /dev/disk/by-uuid/ entries disappear on transition-to-incremental

### ISSUE THREAD

**Issue by crawfxrd** [datto/dattobd#57]
Snapshotting a volume that have a corresponding entry in `/dev/disk/by-{label,uuid}` and then transitioning it to incremental state causes the entry to disappear.

```
> ls /dev/disk/by-uuid/
10711ec6-ac6d-4094-adb9-2d8a2d809e57  6d6325c4-88ba-48a4-b802-5d2b96fc9a75

> dbdctl setup-snapshot /dev/sda1 /boot/cow.snap 1
> ls /dev/disk/by-uuid/
10711ec6-ac6d-4094-adb9-2d8a2d809e57  6d6325c4-88ba-48a4-b802-5d2b96fc9a75

> dbdctl transition-to-incremental 1
> ls /dev/disk/by-uuid/
10711ec6-ac6d-4094-adb9-2d8a2d809e57
```

**Comment by crawfxrd** [comment]
When the snapshot device is created, udev updates the links to point to the snapshot device.
When the snapshot device is destroyed, udev removes the links.

On CentOS 5, it does not add the original device back. The entries can be regenerated with `udevtrigger`.

**Comment by nixomose** [comment]
is this something new? somebody find this or you did?
