### ISSUE TITLE
dattobd module not loaded at boot time on CentOS 6

### ISSUE THREAD

**Issue by ahmgithubahm** [datto/dattobd#58]
The dkms-dattobd rpm built for CentOS (el6) includes a file /etc/modules-load.d/dattobd.conf.  This is in fact the correct location for specifying modules to be loaded at boot time for CentOS 7 (see [this link](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System_Administrators_Guide/sec-Persistent_Module_Loading.html)).  In contrast, for CentOS 6, the file should be at /etc/sysconfig/modules (see [this link](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Deployment_Guide/sec-Persistent_Module_Loading.html)).

Just noticed this after the first reboot since I installed dattobd a few weeks ago.   Everything working fine up until that point, many thanks!

Contents of the new file would be something like:
```
#!/bin/sh

if [ ! -c /dev/datto-ctl ] ; then
	exec /sbin/modprobe dattobd >/dev/null 2>&1
fi
```

**Comment by crawfxrd** [comment]
We've created an internal ticket for this issue. It will be fixed with the next version release.

**Comment by ahmgithubahm** [comment]
Thanks !

**Comment by crawfxrd** [comment]
Sorry for the delay. The 0.9.12 packages are available with the script for CentOS 5 and 6.
