### ISSUE TITLE
Snapshot driver failing with cow file max size exceeded

### ISSUE THREAD

**Issue by venugopalnaidu** [datto/dattobd#87]
dattobd driver failling with cow file size exceed error.

**kernel version** - 2.6.32-358.6.2.el6.x86_64.
**fileSystem** - ext4 (Total Size:- 985G Used:- 514G Free:- 422G)
**CowFile Size** - 100Gb

There is no huge data copies in snapshot mode(less than 2Gb), but after some time driver returning errors as below.

kernel: datto: cow file max size exceeded: -27
kernel: datto: error writing cow data: -27
kernel: datto: error writing cow data and mapping: -27
kernel: datto: error handling write bio: -27

I tried with datto-0.9.10 and datto-0.9.15.

**Comment by nixomose** [comment]
Then likely what's happening is that there are writes going on that you are not aware of.
Some filesystems write metadata to disk every once in a while. atime updates could cause this, too.

**Comment by venugopalnaidu** [comment]
Thanks for the reply,

Why can't the cow file can grow on its own once it reaches max file size. Is there any driver level limitation to resize a cow file.Its happening for me continuously.

**Comment by crawfxrd** [comment]
What is the command you are using to snapshot the volume?
How long do you have the volume in snapshot mode before you get the error?

For why we cannot resize the cow file after creation, see https://github.com/datto/dattobd/pull/10.

**Comment by venugopalnaidu** [comment]
I am getting cow file exceeded error with in 20 min of time after creating snapshot and i understand why the cow file resizing not allowed after creation.

I am using the below command to create a snapshot.

./snapCreator setup-snapshot /dev/sda5 /DataUp/.cowfile.snapshot 2 -f 102400

**Comment by crawfxrd** [comment]
Does this `snapCreator` correctly pass the size to use? (You can check the `fallocate` field in`/proc/datto-info`, which will be in bytes.)

If it does, then there is a lot of writes occurring. You would be able to verify this using a tool like iotop, iostat, or dstat (or some graphical equivalent).

**Comment by crawfxrd** [comment]
Reopen if you still have this issue.

**Comment by ybaskar09** [comment]
Hi 
In the 0.11.9 build, we have the auto-extension feature for the COW file. However, if this feature is used, there is a risk that the server may not have sufficient space to expand the file at the time of extension. Are there any alternative options available to lock the writes to the COW file and prevent this issue?

**Comment by jameykirby** [comment]
The solution is to gracefully teardown the snapshot when this situation
occurs. It is an acceptable solution. At some point, the user will a)
have to snapshot/backup at a less active time or b) migrate to a larger
volume.

**Comment by ybaskar09** [comment]
Hi 
Thanks for the reply.
Tearing down the snapshot is not the solution in my case
I need a mechanism where I can restrict the writes to the cow file during replication.
I have a DB server where it continuously writes data. But increasing the size of the cow file is not the solution as the system might now have sufficient space.
Any mechanism to lock the cow file writes? Or any other approach

**Comment by yito24** [comment]
Hi @ybaskar09 

While a snapshot exists, it is necessary to write change data to COW.
Therefore, COW cannot be locked.
As a workaround, you need to take some measures such as stopping replication before taking a snapshot.
